In [3]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("raw_employee_attrition_data_(inprogress).csv")

Saving raw_employee_attrition_data_(inprogress).csv to raw_employee_attrition_data_(inprogress) (1).csv

# **Inspect** **the** **data**

In [4]:
df.head()

,EmployeeID,Age,Gender,JobRole,TenureYears,PerformanceRating,MonthlySalary,Attrition
0,23056,33.0,Female,Manager,1.0,1.0,9734.51,No
1,47703,33.0,Female,HR Specialist,5.0,4.0,7552.38,No
2,7424,45.0,Male,Manager,0.0,4.0,3931.63,No
3,34697,19.0,Non-Binary,Manager,2.0,3.0,7992.26,No
4,31490,42.0,Male,Manager,1.0,3.0,5215.60,Yes

In [6]:
df.shape

(51500, 8)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51500 entries, 0 to 51499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         51500 non-null  int64
 1   Age                48958 non-null  float64
 2   Gender             51500 non-null  object
 3   JobRole            51500 non-null  object
 4   TenureYears        51500 non-null  float64
 5   PerformanceRating  49953 non-null  float64
 6   MonthlySalary      51500 non-null  float64
 7   Attrition          50467 non-null  object
dtypes: float64(4), int64(1), object(3)
memory usage: 3.1+ MB

In [9]:
df.isnull().sum()

EmployeeID              0
Age                  2542
Gender                  0
JobRole                 0
TenureYears             0
PerformanceRating    1547
MonthlySalary           0
Attrition            1033
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(1500)

In [11]:
df[df.duplicated()]

,EmployeeID,Age,Gender,JobRole,TenureYears,PerformanceRating,MonthlySalary,Attrition
446,23525,39.0,Male,HR Specialist,0.0,4.0,4923.57,No
2149,37243,36.0,Male,Software Engineer,1.0,4.0,5998.15,No
2891,25476,NaN,Male,Software Engineer,4.0,3.0,7353.63,No
3002,44584,29.0,Female,Software Engineer,1.0,2.0,6754.97,Yes
3120,34505,33.0,Female,Software Engineer,0.0,NaN,4808.26,Yes
...,...,...,...,...,...,...,...,...
51383,19700,33.0,Male,HR Specialist,2.0,5.0,5271.66,No
51384,1876,48.0,Female,Data Analyst,7.0,4.0,4214.22,No
51392,49190,44.0,Female,Software Engineer,2.0,3.0,6640.31,Yes
51402,4684,NaN,Female,Data Analyst,25.0,1.0,7093.15,No
51493,9755,30.0,Female,HR Specialist,1.0,3.0,2257.71,No

# **Handle missing values**

In [12]:
df.describe()

,EmployeeID,Age,TenureYears,PerformanceRating,MonthlySalary
count,51500.000000,48958.000000,51500.000000,49953.000000,51500.000000
mean,24990.845748,35.723620,4.524485,3.153905,15801.187914
std,14434.284871,15.454273,4.985129,0.967095,98845.198652
min,1.000000,-9.000000,0.000000,1.000000,-5000.000000
25%,12490.750000,28.000000,1.000000,3.000000,4605.140000
50%,24981.500000,35.000000,3.000000,3.000000,5994.400000
75%,37498.250000,42.000000,6.000000,4.000000,7371.882500
max,50000.000000,150.000000,55.000000,5.000000,999999.000000

In [13]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [15]:
df["Age"].isnull().sum()

np.int64(0)

In [16]:
df["PerformanceRating"].value_counts()

PerformanceRating
3.0    24722
4.0    10140
2.0     7534
5.0     5049
1.0     2508
Name: count, dtype: int64

In [17]:
df["PerformanceRating"] = df["PerformanceRating"].fillna(
    df["PerformanceRating"].mode()[0]
)

In [18]:
df["PerformanceRating"].isnull().sum()

np.int64(0)

In [19]:
df["Attrition"].value_counts(dropna=False)

Attrition
No     37565
Yes    12902
NaN     1033
Name: count, dtype: int64

In [21]:
df[df["Attrition"].isnull()].head()

,EmployeeID,Age,Gender,JobRole,TenureYears,PerformanceRating,MonthlySalary,Attrition
263,13634,34.0,Female,Sales Exec,2.0,5.0,8961.34,NaN
289,28583,21.0,Male,Manager,4.0,3.0,8397.25,NaN
320,5669,17.0,Male,Software Engineer,13.0,2.0,3642.64,NaN
322,37185,23.0,Male,Data Analyst,0.0,3.0,3894.72,NaN
330,46122,34.0,Male,Manager,0.0,3.0,6958.56,NaN

In [22]:
df_clean = df[df["Attrition"].notna()].copy()

In [23]:
missing_attrition = df[df["Attrition"].isna()].copy()

In [24]:
df_clean["Attrition"].value_counts()

Attrition
No     37565
Yes    12902
Name: count, dtype: int64

In [27]:
df_clean.isnull().sum()

EmployeeID           0
Age                  0
Gender               0
JobRole              0
TenureYears          0
PerformanceRating    0
MonthlySalary        0
Attrition            0
dtype: int64

# **Check duplicates**

In [29]:
df_clean["EmployeeID"].duplicated().sum()

np.int64(1467)

In [30]:
df_clean.duplicated().sum()

np.int64(1467)

In [31]:
df_clean = df_clean.drop_duplicates()

In [32]:
print("Duplicate rows:", df_clean.duplicated().sum())
print("Duplicate Employee IDs:", df_clean["EmployeeID"].duplicated().sum())

Duplicate rows: 0
Duplicate Employee IDs: 0

# **Correct data types**

In [33]:
df_clean.dtypes

EmployeeID             int64
Age                  float64
Gender                object
JobRole               object
TenureYears          float64
PerformanceRating    float64
MonthlySalary        float64
Attrition             object
dtype: object

# **Check invalid values, correct them and standerdize**

In [34]:
df_clean.describe()

,EmployeeID,Age,TenureYears,PerformanceRating,MonthlySalary
count,49000.000000,49000.000000,49000.000000,49000.000000,49000.000000
mean,25028.909898,35.690735,4.521041,3.148020,15823.811792
std,14430.279544,15.068907,4.976100,0.951479,98939.857871
min,1.000000,-9.000000,0.000000,1.000000,-5000.000000
25%,12543.750000,28.000000,1.000000,3.000000,4608.252500
50%,25034.500000,35.000000,3.000000,3.000000,5995.715000
75%,37518.250000,41.000000,6.000000,4.000000,7372.012500
max,50000.000000,150.000000,55.000000,5.000000,999999.000000

In [36]:
df_clean["Age"].describe()

count    49000.000000
mean        35.690735
std         15.068907
min         -9.000000
25%         28.000000
50%         35.000000
75%         41.000000
max        150.000000
Name: Age, dtype: float64

In [37]:
df_clean[(df_clean["Age"] < 18) | (df_clean["Age"] > 100)]

,EmployeeID,Age,Gender,JobRole,TenureYears,PerformanceRating,MonthlySalary,Attrition
25,24034,13.0,Male,Sales Exec,1.0,3.0,7256.28,No
35,47910,7.0,Female,HR Specialist,2.0,3.0,7670.30,No
37,33469,150.0,Male,HR Specialist,18.0,5.0,4184.40,No
40,32773,16.0,M,Sales Exec,5.0,4.0,4930.77,No
97,43245,16.0,Male,Sales Exec,8.0,4.0,3802.59,Yes
...,...,...,...,...,...,...,...,...
51382,1540,6.0,Male,Sales Exec,3.0,3.0,6860.58,Yes
51398,34633,16.0,Female,Software Engineer,17.0,3.0,5945.13,No
51417,13315,150.0,Male,Sales Exec,2.0,4.0,6478.40,No
51426,36859,12.0,Male,Data Analyst,2.0,2.0,4671.51,Yes
51460,21397,14.0,Male,Sales Exec,2.0,5.0,8307.63,Yes

In [54]:
df_clean.loc[(df_clean['Age'] < 18 ) | (df_clean['Age'] > 100), 'Age'] = np.nan
df_clean['Age'] = df_clean['Age'].fillna(df_clean['Age'].median())

In [55]:
df_clean["Age"].describe()

count    49000.000000
mean        35.439714
std          8.589157
min         18.000000
25%         30.000000
50%         35.000000
75%         41.000000
max         79.000000
Name: Age, dtype: float64

In [38]:
df_clean[df_clean["TenureYears"] < 0]

Empty DataFrame
Columns: [EmployeeID, Age, Gender, JobRole, TenureYears, PerformanceRating, MonthlySalary, Attrition]
Index: []

In [39]:
df_clean[df_clean["TenureYears"] > df_clean["Age"]]

,EmployeeID,Age,Gender,JobRole,TenureYears,PerformanceRating,MonthlySalary,Attrition
232,28203,15.0,M,Software Engineer,37.0,3.0,12014.70,No
478,19429,14.0,Male,Data Analyst,19.0,3.0,4342.30,Yes
577,25396,9.0,Male,Sales Exec,17.0,2.0,6604.64,No
599,12179,19.0,Male,Software Engineer,20.0,3.0,3322.82,No
669,24956,20.0,Male,Sales Exec,21.0,1.0,3623.85,No
...,...,...,...,...,...,...,...,...
50668,43134,-1.0,Male,HR Specialist,0.0,4.0,8625.62,No
50721,4726,3.0,Male,Manager,4.0,3.0,8352.14,Yes
50991,17178,10.0,Male,Manager,12.0,3.0,6497.02,No
51204,39177,0.0,Non-Binary,HR Specialist,4.0,2.0,3853.96,Yes
51398,34633,16.0,Female,Software Engineer,17.0,3.0,5945.13,No

In [56]:
df_clean[df_clean["TenureYears"] > df_clean["Age"]][["Age", "TenureYears"]]

        Age  TenureYears
232    35.0         37.0
599    19.0         20.0
669    20.0         21.0
675    19.0         26.0
1453   22.0         27.0
...     ...          ...
49376  26.0         32.0
49405  25.0         29.0
49621  19.0         21.0
49744  21.0         25.0
50102  21.0         22.0

[108 rows x 2 columns]

In [57]:
df_clean.loc[
    df_clean["TenureYears"] > df_clean["Age"],
    "Age"
].value_counts().sort_index()

Age
18.0     6
19.0     7
20.0     9
21.0    10
22.0     9
23.0     8
24.0     6
25.0     8
26.0     7
27.0     5
28.0     5
29.0     7
30.0     1
31.0     4
32.0     3
33.0     1
34.0     2
35.0     8
38.0     1
39.0     1
Name: count, dtype: int64

In [65]:
df_clean["Age_Invalid"] = (
    df_clean["TenureYears"] > df_clean["Age"] - 18
)
df_clean

,EmployeeID,Age,Gender,JobRole,TenureYears,PerformanceRating,MonthlySalary,Attrition,Age_Invalid,StartAge
0,23056,33.0,Female,Manager,1.0,1.0,9734.51,No,False,32.0
1,47703,33.0,Female,HR Specialist,5.0,4.0,7552.38,No,False,28.0
2,7424,45.0,Male,Manager,0.0,4.0,3931.63,No,False,45.0
3,34697,19.0,Non-Binary,Manager,2.0,3.0,7992.26,No,True,17.0
4,31490,42.0,Male,Manager,1.0,3.0,5215.60,Yes,False,41.0
...,...,...,...,...,...,...,...,...,...,...
51495,32557,42.0,Male,Manager,8.0,3.0,9447.82,No,False,34.0
51496,47691,27.0,Non-Binary,Sales Exec,2.0,4.0,3307.01,No,False,25.0
51497,35723,38.0,Male,Software Engineer,3.0,5.0,4214.57,No,False,35.0
51498,25913,44.0,Female,Manager,4.0,4.0,6887.79,No,False,40.0
51499,3851,29.0,Female,Manager,7.0,2.0,3980.43,No,False,22.0

In [66]:
df_clean["Age_Invalid"].value_counts()

Age_Invalid
False    44977
True      4023
Name: count, dtype: int64

In [67]:
df_clean[df_clean["Age_Invalid"]][
    ["Age", "TenureYears"]
].sort_values("TenureYears", ascending=False).head(20)

        Age  TenureYears
28002  38.0         55.0
31157  22.0         50.0
41217  63.0         50.0
6345   27.0         50.0
31181  35.0         49.0
5871   32.0         47.0
19304  26.0         47.0
25848  34.0         47.0
8746   35.0         45.0
38512  35.0         45.0
3197   28.0         43.0
31110  49.0         43.0
15415  20.0         43.0
44346  31.0         43.0
8172   34.0         41.0
17235  35.0         41.0
11817  26.0         41.0
2379   27.0         41.0
13122  39.0         40.0
34373  29.0         40.0

In [68]:
df_clean["StartAge"] = df_clean["Age"] - df_clean["TenureYears"]

In [69]:
df_clean[df_clean["Age_Invalid"]][
    ["Age", "TenureYears", "StartAge"]
].head(20)

      Age  TenureYears  StartAge
3    19.0          2.0      17.0
17   30.0         16.0      14.0
20   23.0          8.0      15.0
37   35.0         18.0      17.0
38   25.0         15.0      10.0
39   22.0          6.0      16.0
47   18.0          2.0      16.0
63   21.0         14.0       7.0
75   19.0         13.0       6.0
78   22.0          9.0      13.0
89   29.0         14.0      15.0
98   26.0         15.0      11.0
100  18.0          3.0      15.0
114  20.0          5.0      15.0
136  29.0         13.0      16.0
151  23.0         13.0      10.0
165  25.0         12.0      13.0
176  18.0         10.0       8.0
177  26.0         14.0      12.0
178  22.0         10.0      12.0

In [76]:
df_clean["Age_Invalid"] = (
    ((df_clean["Age"] - df_clean["TenureYears"]) < 18)
)

In [80]:
df_clean.loc[
    df_clean['TenureYears'] > df_clean['Age'],
    'Age'
] = np.nan
df_clean['Age'] = df_clean['Age'].fillna(df_clean['Age'].median())

In [81]:
df_clean["Age"].isna().sum()

np.int64(0)

In [84]:
df_clean["Age"].describe()

count    49000.000000
mean        36.269184
std          7.832328
min         18.000000
25%         32.000000
50%         35.000000
75%         41.000000
max         79.000000
Name: Age, dtype: float64

In [40]:
df_clean[
    (df_clean["PerformanceRating"] < 1) |
    (df_clean["PerformanceRating"] > 5)
]

Empty DataFrame
Columns: [EmployeeID, Age, Gender, JobRole, TenureYears, PerformanceRating, MonthlySalary, Attrition]
Index: []

In [42]:
df_clean[df_clean["MonthlySalary"] < 0]

,EmployeeID,Age,Gender,JobRole,TenureYears,PerformanceRating,MonthlySalary,Attrition
111,7301,28.0,Male,Manager,6.0,4.0,-5000.00,No
131,25508,55.0,Male,HR Specialist,15.0,5.0,-5000.00,No
188,46692,17.0,Female,Software Engineer,0.0,2.0,-398.44,No
204,35646,38.0,M,Manager,2.0,2.0,-5000.00,No
278,47993,35.0,Male,HR Specialist,1.0,3.0,-5000.00,Yes
...,...,...,...,...,...,...,...,...
51168,3601,26.0,Female,HR Specialist,0.0,4.0,-5000.00,Yes
51232,40003,33.0,Non-Binary,Sales Exec,10.0,5.0,-5000.00,No
51263,6369,26.0,Non-Binary,HR Specialist,5.0,5.0,-5000.00,No
51291,32433,45.0,Female,HR Specialist,7.0,3.0,-5000.00,Yes
51351,16079,34.0,Male,Data Analyst,1.0,4.0,-5000.00,Yes

In [46]:
df_clean.nlargest(20, "MonthlySalary")[["EmployeeID", "MonthlySalary"]]

      EmployeeID  MonthlySalary
409        13818       999999.0
444        43781       999999.0
893        21448       999999.0
954        22009       999999.0
994        13587       999999.0
1034        7347       999999.0
1111       17955       999999.0
1400       42389       999999.0
1710       10473       999999.0
1877        7269       999999.0
1925       15394       999999.0
2036       31781       999999.0
2052        8483       999999.0
2441       25580       999999.0
2500       27380       999999.0
2527       43842       999999.0
2542       41177       999999.0
2580       19263       999999.0
2839       44385       999999.0
2924         848       999999.0

In [47]:
(df_clean["MonthlySalary"] == 999999).sum()

np.int64(490)

In [49]:
import numpy as np

df_clean["MonthlySalary"] = df_clean["MonthlySalary"].replace(999999, np.nan)

In [50]:
df_clean["MonthlySalary"].isnull().sum()

np.int64(490)

In [51]:
(df_clean["MonthlySalary"] < 0).sum()

np.int64(541)

In [85]:
df_clean.loc[
    (df_clean['MonthlySalary'] < 0),
    'MonthlySalary'
] = np.nan

In [86]:
df_clean['MonthlySalary'] = df_clean['MonthlySalary'].fillna(
    df_clean['MonthlySalary'].median()
)

In [87]:
df_clean["MonthlySalary"].describe()

count    49000.000000
mean      5999.236893
std       1957.551040
min          0.290000
25%       4675.982500
50%       5998.370000
75%       7310.862500
max      15168.700000
Name: MonthlySalary, dtype: float64

In [43]:
df_clean["Gender"].value_counts()

Gender
Male          24342
Female        17776
F              2454
M              2326
Non-Binary     2102
Name: count, dtype: int64

In [88]:
df_clean['Gender'] = df_clean['Gender'].replace({
    'M': 'Male',
    'F': 'Female'
})

In [89]:
df_clean["Gender"].value_counts()

Gender
Male          26668
Female        20230
Non-Binary     2102
Name: count, dtype: int64

In [44]:
df_clean["JobRole"].value_counts()

JobRole
Data Analyst         9706
HR Specialist        9624
Sales Exec           9583
Software Engineer    9583
Manager              9518
software engineer     986
Name: count, dtype: int64

In [90]:
df_clean['JobRole'] = df_clean['JobRole'].replace({
    'software engineer': 'Software Engineer'
})

In [91]:
df_clean['JobRole'].value_counts()

JobRole
Software Engineer    10569
Data Analyst          9706
HR Specialist         9624
Sales Exec            9583
Manager               9518
Name: count, dtype: int64

In [45]:
df_clean["Attrition"].value_counts()

Attrition
No     36470
Yes    12530
Name: count, dtype: int64

# **Validate cleaned data set**

In [92]:
df_clean.isnull().sum()

EmployeeID           0
Age                  0
Gender               0
JobRole              0
TenureYears          0
PerformanceRating    0
MonthlySalary        0
Attrition            0
Age_Invalid          0
StartAge             0
dtype: int64

In [93]:
df_clean.duplicated().sum()

np.int64(0)

In [94]:
df_clean['EmployeeID'].is_unique

True

In [95]:
df_clean['Age'].min(), df_clean['Age'].max()

(18.0, 79.0)

In [96]:
df_clean['TenureYears'].min(), df_clean['TenureYears'].max()

(0.0, 55.0)

In [97]:
(df_clean['TenureYears'] > df_clean['Age']).sum()

np.int64(40)

In [98]:
df_clean.loc[
    df_clean['TenureYears'] > df_clean['Age'],
    'Age'
] = np.nan

df_clean['Age'] = df_clean['Age'].fillna(df_clean['Age'].median())

In [99]:
(df_clean['TenureYears'] > df_clean['Age']).sum()

np.int64(40)

In [100]:
df_clean.loc[
    df_clean['TenureYears'] > df_clean['Age'],
    'Age'
] = df_clean['TenureYears']

In [101]:
(df_clean['TenureYears'] > df_clean['Age']).sum()

np.int64(0)

In [102]:
print(df_clean['MonthlySalary'].min())
print((df_clean['MonthlySalary'] < 0).sum())
print((df_clean['MonthlySalary'] == 999999).sum())

0.29
0
0

In [103]:
df_clean['Gender'].value_counts()

Gender
Male          26668
Female        20230
Non-Binary     2102
Name: count, dtype: int64

In [104]:
df_clean['JobRole'].value_counts()

JobRole
Software Engineer    10569
Data Analyst          9706
HR Specialist         9624
Sales Exec            9583
Manager               9518
Name: count, dtype: int64

# **Documentation**

In [105]:
cleaning_log = {
    "Age": [
        "Replaced values below 18 or above 100 with median",
        "Replaced invalid Age values where TenureYears > Age with median",
        "Filled missing Age values with the median"
    ],

    "MonthlySalary": [
        "Replaced negative salaries with median",
        "Replaced 999999 salary values with median",
        "Filled missing salary values with the median"
    ],

    "Gender": [
        "Standardized M to Male",
        "Standardized F to Female"
    ],

    "JobRole": [
        "Standardized 'software engineer' to 'Software Engineer'"
    ]
}

for column, changes in cleaning_log.items():
    print(f"\n{column}:")
    for change in changes:
        print("-", change)

Age:
- Replaced values below 18 or above 100 with median
- Replaced invalid Age values where TenureYears > Age with median
- Filled missing Age values with the median

MonthlySalary:
- Replaced negative salaries with median
- Replaced 999999 salary values with median
- Filled missing salary values with the median

Gender:
- Standardized M to Male
- Standardized F to Female

JobRole:
- Standardized 'software engineer' to 'Software Engineer'

In [110]:
df_clean = df_clean.drop(columns=['Age_Invalid', 'StartAge'])

In [111]:
df_clean.columns

Index(['EmployeeID', 'Age', 'Gender', 'JobRole', 'TenureYears',
       'PerformanceRating', 'MonthlySalary', 'Attrition'],
      dtype='object')

In [112]:
df_clean.to_csv('df_clean.csv', index=False)

In [113]:
import os

os.path.exists('df_clean.csv')

True

In [114]:
from google.colab import files

files.download('df_clean.csv')